spring:
  thymeleaf:
    cache: false

dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://192.168.72.128:2181
  #没有服务端也能发布
  consumer:
    check: false

#分布式文件系统
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
   - 192.168.72.128:22122
server:
  ip: 192.168.72.128
