server:
  port: 8081
spring:
  thymeleaf:
    cache: false

dubbo:
  consumer:
    #没有服务端也能发布
    check: false
  registry:
    address: zookeeper://192.168.72.128:2181
  application:
    name: shop_front
